# Generated by Django 5.0.2 on 2024-03-03 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouporder',
            name='total_price',
        ),
        migrations.AddField(
            model_name='grouporder',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('complete', 'complete')], default='pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='grouporder',
            name='payer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.user'),
        ),
    ]
