# Generated by Django 5.0.2 on 2024-03-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_grouporder_total_price_grouporder_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='net_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
